# Generated by Django 5.2.14 on 2026-05-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα έργου')),
                ('client_name', models.CharField(max_length=200, verbose_name='Πελάτης')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Διεύθυνση')),
                ('status', models.CharField(choices=[('quote', 'Προσφορά'), ('in_progress', 'Σε εξέλιξη'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρωμένο')], default='quote', max_length=20, verbose_name='Κατάσταση')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ημ. έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημ. ολοκλήρωσης')),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Προσφορά (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Έργο',
                'verbose_name_plural': 'Έργα',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό (€)')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('income_type', models.CharField(choices=[('deposit', 'Προκαταβολή'), ('invoice', 'Τιμολόγιο'), ('final', 'Εξόφληση'), ('other', 'Άλλο')], default='invoice', max_length=20, verbose_name='Τύπος')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Έσοδο',
                'verbose_name_plural': 'Έσοδα',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('materials', 'Υλικά'), ('labor', 'Εργατικά'), ('subcontractor', 'Υπεργολάβος'), ('transport', 'Μεταφορικά'), ('equipment', 'Εξοπλισμός'), ('other', 'Άλλο')], default='materials', max_length=20, verbose_name='Κατηγορία')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό (€)')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Προμηθευτής')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Έξοδο',
                'verbose_name_plural': 'Έξοδα',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
