# Generated by Django 5.2.14 on 2026-05-31 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accounting', 'Λογιστικά / Φορολογικά'), ('insurance', 'Ασφάλειες'), ('rent', 'Ενοίκιο / Χώρος'), ('utilities', 'Ρεύμα / Ύδρευση / Τηλέφωνα'), ('vehicle', 'Όχημα / Καύσιμα / Σέρβις'), ('tools', 'Εργαλεία / Εξοπλισμός'), ('subscriptions', 'Συνδρομές / Λογισμικό'), ('other', 'Άλλο')], default='other', max_length=20, verbose_name='Κατηγορία')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό (€)')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Προμηθευτής / Πάροχος')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Λειτουργικό έξοδο',
                'verbose_name_plural': 'Λειτουργικά έξοδα',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Έξοδο έργου', 'verbose_name_plural': 'Έξοδα έργων'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Έσοδο έργου', 'verbose_name_plural': 'Έσοδα έργων'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='Έργο (cost center)'),
        ),
    ]
