# Generated by Django 5.2.14 on 2026-05-31 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_operationalexpense_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('hours', models.DecimalField(decimal_places=2, help_text='π.χ. 8 ή 4.5', max_digits=6, verbose_name='Ώρες')),
                ('worker', models.CharField(blank=True, help_text='Όνομα συνεργάτη ή βοηθητικού', max_length=100, verbose_name='Εργαζόμενος')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Περιγραφή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Εργατοώρα',
                'verbose_name_plural': 'Εργατοώρες',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
