# Generated by Django 5.2.14 on 2026-05-31 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_workhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Αρ. προσφοράς')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος / Έργο')),
                ('client_name', models.CharField(max_length=200, verbose_name='Πελάτης')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Τηλέφωνο')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Διεύθυνση')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Ισχύς έως')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('sent', 'Απεσταλμένη'), ('accepted', 'Αποδεκτή'), ('rejected', 'Απορριφθείσα')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις / Όροι')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='projects.project', verbose_name='Συνδεδεμένο έργο')),
            ],
            options={
                'verbose_name': 'Προσφορά',
                'verbose_name_plural': 'Προσφορές',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Περιγραφή')),
                ('category', models.CharField(choices=[('materials', 'Υλικά'), ('labor', 'Εργατικά'), ('subcontractor', 'Υπεργολάβος'), ('equipment', 'Εξοπλισμός'), ('other', 'Άλλο')], default='materials', max_length=20, verbose_name='Κατηγορία')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ποσότητα')),
                ('unit', models.CharField(choices=[('piece', 'τμχ'), ('meter', 'μέτρο'), ('hour', 'ώρα'), ('set', 'σετ'), ('lump', 'διάφορα')], default='piece', max_length=10, verbose_name='Μονάδα')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή μονάδας (€)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.quote', verbose_name='Προσφορά')),
            ],
            options={
                'verbose_name': 'Γραμμή προσφοράς',
                'verbose_name_plural': 'Γραμμές προσφοράς',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
