# Generated by Django 5.2.14 on 2026-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_quote_requires_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vibe Electrician', max_length=200, verbose_name='Επωνυμία')),
                ('tagline', models.CharField(blank=True, default='Ηλεκτρολογικές Εγκαταστάσεις', max_length=200, verbose_name='Υπότιτλος')),
                ('logo', models.ImageField(blank=True, upload_to='company/', verbose_name='Λογότυπο')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Διεύθυνση')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('vat', models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Στοιχεία εταιρείας',
                'verbose_name_plural': 'Στοιχεία εταιρείας',
            },
        ),
    ]
