# Generated by Django 5.2.14 on 2026-05-31 16:55

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_quote_project_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Προτεινόμενο: 360×112 px (PNG διαφανές). Εμφάνιση στο PDF: έως 180×56 px.', upload_to='company/', verbose_name='Λογότυπο'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=projects.models.default_local_date, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=projects.models.default_local_date, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='operationalexpense',
            name='date',
            field=models.DateField(default=projects.models.default_local_date, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(default=projects.models.default_local_date, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='date',
            field=models.DateField(default=projects.models.default_local_date, verbose_name='Ημερομηνία'),
        ),
    ]
