# Generated by Django 5.2.14 on 2026-06-01 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_quote_client_vat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('quote_created', 'Δημιουργία προσφοράς'), ('quote_updated', 'Επεξεργασία προσφοράς'), ('quote_deleted', 'Διαγραφή προσφοράς')], max_length=40, verbose_name='Ενέργεια')),
                ('object_type', models.CharField(max_length=40, verbose_name='Τύπος αντικειμένου')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID αντικειμένου')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Αντικείμενο')),
                ('summary', models.CharField(max_length=300, verbose_name='Σύνοψη')),
                ('details', models.JSONField(blank=True, default=list, help_text='Λίστα αλλαγών (πεδία προσφοράς / γραμμές).', verbose_name='Λεπτομέρειες αλλαγών')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Κίνηση',
                'verbose_name_plural': 'Κινήσεις (log)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='projects_ac_created_9048e2_idx'), models.Index(fields=['object_type', 'object_id'], name='projects_ac_object__d01971_idx'), models.Index(fields=['action'], name='projects_ac_action_879a68_idx')],
            },
        ),
    ]
