# Generated by Django 5.2.14 on 2026-06-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('quote_created', 'Δημιουργία προσφοράς'), ('quote_updated', 'Επεξεργασία προσφοράς'), ('quote_deleted', 'Διαγραφή προσφοράς'), ('project_created', 'Δημιουργία έργου'), ('project_updated', 'Επεξεργασία έργου'), ('project_deleted', 'Διαγραφή έργου'), ('income_created', 'Καταχώρηση εσόδου'), ('income_updated', 'Επεξεργασία εσόδου'), ('income_deleted', 'Διαγραφή εσόδου'), ('expense_created', 'Καταχώρηση εξόδου έργου'), ('expense_updated', 'Επεξεργασία εξόδου έργου'), ('expense_deleted', 'Διαγραφή εξόδου έργου'), ('work_hours_created', 'Καταχώρηση εργατοωρών'), ('operational_expense_created', 'Καταχώρηση λειτουργικού εξόδου'), ('customer_created', 'Δημιουργία πελάτη'), ('customer_updated', 'Επεξεργασία πελάτη'), ('customer_deactivated', 'Απενεργοποίηση πελάτη')], max_length=40, verbose_name='Ενέργεια'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα / Επωνυμία')),
                ('vat', models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Διεύθυνση')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Πελάτης',
                'verbose_name_plural': 'Πελάτες',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='projects_cu_name_e8008d_idx'), models.Index(fields=['vat'], name='projects_cu_vat_5dbd09_idx')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.customer', verbose_name='Πελάτης (πελατολόγιο)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='projects.customer', verbose_name='Πελάτης (πελατολόγιο)'),
        ),
    ]
