# Generated by Django 5.2.14 on 2026-06-19 19:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_customer_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='manual_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Αν συμπληρωθεί, υπερισχύει του αθροίσματος των γραμμών.', max_digits=10, null=True, verbose_name='Σύνολο (χειροκίνητο)'),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Τιμή μονάδας (€)'),
        ),
    ]
