# Generated by Django 5.2.14 on 2026-06-19 19:57

import django.db.models.deletion
import projects.models
from django.db import migrations, models


LOOKUP_SEEDS = [
    (
        "income_type",
        [
            ("deposit", "Προκαταβολή", 0),
            ("invoice", "Τιμολόγιο", 1),
            ("final", "Εξόφληση", 2),
            ("other", "Άλλο", 3),
        ],
    ),
    (
        "project_expense",
        [
            ("materials", "Υλικά", 0),
            ("labor", "Εργατικά", 1),
            ("subcontractor", "Υπεργολάβος", 2),
            ("transport", "Μεταφορικά", 3),
            ("equipment", "Εξοπλισμός", 4),
            ("other", "Άλλο", 5),
        ],
    ),
    (
        "operational_expense",
        [
            ("accounting", "Λογιστικά / Φορολογικά", 0),
            ("insurance", "Ασφάλειες", 1),
            ("rent", "Ενοίκιο / Χώρος", 2),
            ("utilities", "Ρεύμα / Ύδρευση / Τηλέφωνα", 3),
            ("vehicle", "Όχημα / Καύσιμα / Σέρβις", 4),
            ("tools", "Εργαλεία / Εξοπλισμός", 5),
            ("subscriptions", "Συνδρομές / Λογισμικό", 6),
            ("other", "Άλλο", 7),
        ],
    ),
    (
        "quote_line_category",
        [
            ("materials", "Υλικά", 0),
            ("labor", "Εργατικά", 1),
            ("subcontractor", "Υπεργολάβος", 2),
            ("equipment", "Εξοπλισμός", 3),
            ("other", "Άλλο", 4),
        ],
    ),
    (
        "quote_unit",
        [
            ("piece", "τμχ", 0),
            ("meter", "μέτρο", 1),
            ("hour", "ώρα", 2),
            ("set", "σετ", 3),
            ("lump", "διάφορα", 4),
        ],
    ),
]


def seed_lookup_options(apps, schema_editor):
    LookupOption = apps.get_model("projects", "LookupOption")
    for group, items in LOOKUP_SEEDS:
        for code, label, sort_order in items:
            LookupOption.objects.get_or_create(
                group=group,
                code=code,
                defaults={
                    "label": label,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )


def _option_map(apps, group):
    LookupOption = apps.get_model("projects", "LookupOption")
    return {
        row.code: row.pk
        for row in LookupOption.objects.filter(group=group).only("pk", "code")
    }


def migrate_income_types(apps, schema_editor):
    Income = apps.get_model("projects", "Income")
    options = _option_map(apps, "income_type")
    default_pk = options.get("invoice")
    for income in Income.objects.all().iterator():
        income.income_type_id = options.get(income.income_type_legacy, default_pk)
        income.save(update_fields=["income_type_id"])


def migrate_expense_categories(apps, schema_editor):
    Expense = apps.get_model("projects", "Expense")
    options = _option_map(apps, "project_expense")
    default_pk = options.get("materials")
    for expense in Expense.objects.all().iterator():
        expense.category_id = options.get(expense.category_legacy, default_pk)
        expense.save(update_fields=["category_id"])


def migrate_operational_categories(apps, schema_editor):
    OperationalExpense = apps.get_model("projects", "OperationalExpense")
    options = _option_map(apps, "operational_expense")
    default_pk = options.get("other")
    for expense in OperationalExpense.objects.all().iterator():
        expense.category_id = options.get(expense.category_legacy, default_pk)
        expense.save(update_fields=["category_id"])


def migrate_quote_line_lookups(apps, schema_editor):
    QuoteLineItem = apps.get_model("projects", "QuoteLineItem")
    category_options = _option_map(apps, "quote_line_category")
    unit_options = _option_map(apps, "quote_unit")
    default_category = category_options.get("materials")
    default_unit = unit_options.get("piece")
    for line in QuoteLineItem.objects.all().iterator():
        line.category_id = category_options.get(line.category_legacy, default_category)
        line.unit_id = unit_options.get(line.unit_legacy, default_unit)
        line.save(update_fields=["category_id", "unit_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_quote_optional_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("income_type", "Τύπος εσόδου"),
                            ("project_expense", "Κατηγορία εξόδου έργου"),
                            ("operational_expense", "Κατηγορία λειτουργικού εξόδου"),
                            ("quote_line_category", "Κατηγορία γραμμής προσφοράς"),
                            ("quote_unit", "Μονάδα μέτρησης προσφοράς"),
                        ],
                        editable=False,
                        max_length=30,
                        verbose_name="Ομάδα",
                    ),
                ),
                ("code", models.SlugField(max_length=40, verbose_name="Κωδικός")),
                ("label", models.CharField(max_length=100, verbose_name="Ετικέτα")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Σειρά"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ενεργή"),
                ),
            ],
            options={
                "verbose_name": "Επιλογή λίστας",
                "verbose_name_plural": "Επιλογές λιστών",
                "ordering": ["group", "sort_order", "label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "code"),
                        name="uniq_lookup_group_code",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_lookup_options, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="income",
            old_name="income_type",
            new_name="income_type_legacy",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="category",
            new_name="category_legacy",
        ),
        migrations.RenameField(
            model_name="operationalexpense",
            old_name="category",
            new_name="category_legacy",
        ),
        migrations.RenameField(
            model_name="quotelineitem",
            old_name="category",
            new_name="category_legacy",
        ),
        migrations.RenameField(
            model_name="quotelineitem",
            old_name="unit",
            new_name="unit_legacy",
        ),
        migrations.AddField(
            model_name="income",
            name="income_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incomes",
                to="projects.lookupoption",
                verbose_name="Τύπος",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_expenses",
                to="projects.lookupoption",
                verbose_name="Κατηγορία",
            ),
        ),
        migrations.AddField(
            model_name="operationalexpense",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_expenses",
                to="projects.lookupoption",
                verbose_name="Κατηγορία",
            ),
        ),
        migrations.AddField(
            model_name="quotelineitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_line_categories",
                to="projects.lookupoption",
                verbose_name="Κατηγορία",
            ),
        ),
        migrations.AddField(
            model_name="quotelineitem",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_line_units",
                to="projects.lookupoption",
                verbose_name="Μονάδα",
            ),
        ),
        migrations.RunPython(migrate_income_types, migrations.RunPython.noop),
        migrations.RunPython(migrate_expense_categories, migrations.RunPython.noop),
        migrations.RunPython(migrate_operational_categories, migrations.RunPython.noop),
        migrations.RunPython(migrate_quote_line_lookups, migrations.RunPython.noop),
        migrations.RemoveField(model_name="income", name="income_type_legacy"),
        migrations.RemoveField(model_name="expense", name="category_legacy"),
        migrations.RemoveField(model_name="operationalexpense", name="category_legacy"),
        migrations.RemoveField(model_name="quotelineitem", name="category_legacy"),
        migrations.RemoveField(model_name="quotelineitem", name="unit_legacy"),
        migrations.AlterField(
            model_name="income",
            name="income_type",
            field=models.ForeignKey(
                default=projects.models.default_income_type_id,
                limit_choices_to={"group": "income_type"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incomes",
                to="projects.lookupoption",
                verbose_name="Τύπος",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                default=projects.models.default_project_expense_category_id,
                limit_choices_to={"group": "project_expense"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_expenses",
                to="projects.lookupoption",
                verbose_name="Κατηγορία",
            ),
        ),
        migrations.AlterField(
            model_name="operationalexpense",
            name="category",
            field=models.ForeignKey(
                default=projects.models.default_operational_expense_category_id,
                limit_choices_to={"group": "operational_expense"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_expenses",
                to="projects.lookupoption",
                verbose_name="Κατηγορία",
            ),
        ),
        migrations.AlterField(
            model_name="quotelineitem",
            name="category",
            field=models.ForeignKey(
                default=projects.models.default_quote_line_category_id,
                limit_choices_to={"group": "quote_line_category"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_line_categories",
                to="projects.lookupoption",
                verbose_name="Κατηγορία",
            ),
        ),
        migrations.AlterField(
            model_name="quotelineitem",
            name="unit",
            field=models.ForeignKey(
                default=projects.models.default_quote_unit_id,
                limit_choices_to={"group": "quote_unit"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_line_units",
                to="projects.lookupoption",
                verbose_name="Μονάδα",
            ),
        ),
        migrations.CreateModel(
            name="IncomeTypeOption",
            fields=[],
            options={
                "verbose_name": "Τύπος εσόδου",
                "verbose_name_plural": "Τύποι εσόδου",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.lookupoption",),
        ),
        migrations.CreateModel(
            name="OperationalExpenseCategoryOption",
            fields=[],
            options={
                "verbose_name": "Κατηγορία λειτουργικού εξόδου",
                "verbose_name_plural": "Κατηγορίες λειτουργικού εξόδου",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.lookupoption",),
        ),
        migrations.CreateModel(
            name="ProjectExpenseCategoryOption",
            fields=[],
            options={
                "verbose_name": "Κατηγορία εξόδου έργου",
                "verbose_name_plural": "Κατηγορίες εξόδου έργου",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.lookupoption",),
        ),
        migrations.CreateModel(
            name="QuoteLineCategoryOption",
            fields=[],
            options={
                "verbose_name": "Κατηγορία γραμμής προσφοράς",
                "verbose_name_plural": "Κατηγορίες γραμμής προσφοράς",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.lookupoption",),
        ),
        migrations.CreateModel(
            name="QuoteUnitOption",
            fields=[],
            options={
                "verbose_name": "Μονάδα μέτρησης",
                "verbose_name_plural": "Μονάδες μέτρησης",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.lookupoption",),
        ),
    ]
