# Generated by Django 5.2.14 on 2026-06-19 20:05

import django.db.models.deletion
import projects.models
from django.db import migrations, models


def seed_payment_types(apps, schema_editor):
    LookupOption = apps.get_model("projects", "LookupOption")
    for code, label, sort_order in [
        ("cash", "Μετρητά", 0),
        ("card", "Κάρτα", 1),
    ]:
        LookupOption.objects.get_or_create(
            group="payment_type",
            code=code,
            defaults={
                "label": label,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_lookup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lookupoption",
            name="code",
            field=models.SlugField(
                help_text="Μόνιμος κωδικός (λατινικά, π.χ. invoice). Μην τον αλλάζεις μετά τη χρήση.",
                max_length=40,
                verbose_name="Κωδικός",
            ),
        ),
        migrations.AlterField(
            model_name="lookupoption",
            name="group",
            field=models.CharField(
                choices=[
                    ("income_type", "Τύπος εσόδου"),
                    ("payment_type", "Τύπος πληρωμής"),
                    ("project_expense", "Κατηγορία εξόδου έργου"),
                    ("operational_expense", "Κατηγορία λειτουργικού εξόδου"),
                    ("quote_line_category", "Κατηγορία γραμμής προσφοράς"),
                    ("quote_unit", "Μονάδα μέτρησης προσφοράς"),
                ],
                editable=False,
                max_length=30,
                verbose_name="Ομάδα",
            ),
        ),
        migrations.RunPython(seed_payment_types, migrations.RunPython.noop),
        migrations.AddField(
            model_name="income",
            name="payment_method",
            field=models.ForeignKey(
                default=projects.models.default_payment_method_id,
                limit_choices_to={"group": "payment_type"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="income_payments",
                to="projects.lookupoption",
                verbose_name="Τύπος πληρωμής",
            ),
        ),
        migrations.CreateModel(
            name="IncomePaymentTypeOption",
            fields=[],
            options={
                "verbose_name": "Τύπος πληρωμής",
                "verbose_name_plural": "Τύποι πληρωμής",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("projects.lookupoption",),
        ),
    ]
