# Generated by Django 5.2.14 on 2026-06-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_income_payment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomePaymentTypeOption',
        ),
        migrations.DeleteModel(
            name='IncomeTypeOption',
        ),
        migrations.DeleteModel(
            name='OperationalExpenseCategoryOption',
        ),
        migrations.DeleteModel(
            name='ProjectExpenseCategoryOption',
        ),
        migrations.DeleteModel(
            name='QuoteLineCategoryOption',
        ),
        migrations.DeleteModel(
            name='QuoteUnitOption',
        ),
    ]
