# Generated by Django 5.2.14 on 2026-06-19 21:17

import django.db.models.deletion
import projects.models
from django.db import migrations, models


def seed_operational_income_categories(apps, schema_editor):
    LookupOption = apps.get_model("projects", "LookupOption")
    for code, label, sort_order in [
        ("tax_refund", "Επιστροφή φόρου", 0),
        ("subsidy", "Επιδοτήσεις", 1),
        ("insurance_refund", "Επιστροφή ασφάλισης", 2),
        ("grant", "Επιχορήγηση", 3),
        ("other", "Άλλο", 4),
    ]:
        LookupOption.objects.get_or_create(
            group="operational_income",
            code=code,
            defaults={
                "label": label,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_delete_incomepaymenttypeoption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("quote_created", "Δημιουργία προσφοράς"),
                    ("quote_updated", "Επεξεργασία προσφοράς"),
                    ("quote_deleted", "Διαγραφή προσφοράς"),
                    ("project_created", "Δημιουργία έργου"),
                    ("project_updated", "Επεξεργασία έργου"),
                    ("project_deleted", "Διαγραφή έργου"),
                    ("income_created", "Καταχώρηση εσόδου"),
                    ("income_updated", "Επεξεργασία εσόδου"),
                    ("income_deleted", "Διαγραφή εσόδου"),
                    ("expense_created", "Καταχώρηση εξόδου έργου"),
                    ("expense_updated", "Επεξεργασία εξόδου έργου"),
                    ("expense_deleted", "Διαγραφή εξόδου έργου"),
                    ("work_hours_created", "Καταχώρηση εργατοωρών"),
                    ("operational_expense_created", "Καταχώρηση λειτουργικού εξόδου"),
                    ("operational_income_created", "Καταχώρηση λειτουργικού εσόδου"),
                    ("customer_created", "Δημιουργία πελάτη"),
                    ("customer_updated", "Επεξεργασία πελάτη"),
                    ("customer_deactivated", "Απενεργοποίηση πελάτη"),
                ],
                max_length=40,
                verbose_name="Ενέργεια",
            ),
        ),
        migrations.AlterField(
            model_name="lookupoption",
            name="group",
            field=models.CharField(
                choices=[
                    ("income_type", "Τύπος εσόδου"),
                    ("payment_type", "Τύπος πληρωμής"),
                    ("project_expense", "Κατηγορία εξόδου έργου"),
                    ("operational_expense", "Κατηγορία λειτουργικού εξόδου"),
                    ("operational_income", "Κατηγορία λειτουργικού εσόδου"),
                    ("quote_line_category", "Κατηγορία γραμμής προσφοράς"),
                    ("quote_unit", "Μονάδα μέτρησης προσφοράς"),
                ],
                editable=False,
                max_length=30,
                verbose_name="Ομάδα",
            ),
        ),
        migrations.RunPython(seed_operational_income_categories, migrations.RunPython.noop),
        migrations.CreateModel(
            name="OperationalIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ποσό (€)"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=projects.models.default_local_date,
                        verbose_name="Ημερομηνία",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Πηγή / Φορέας"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Περιγραφή"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=projects.models.default_operational_income_category_id,
                        limit_choices_to={"group": "operational_income"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_incomes",
                        to="projects.lookupoption",
                        verbose_name="Κατηγορία",
                    ),
                ),
            ],
            options={
                "verbose_name": "Λειτουργικό έσοδο",
                "verbose_name_plural": "Λειτουργικά έσοδα",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
