# Generated by Django 5.2.14 on 2026-06-01

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_operational_income"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Τίτλος")),
                (
                    "date",
                    models.DateField(
                        default=projects.models.default_local_date,
                        verbose_name="Ημερομηνία",
                    ),
                ),
                ("all_day", models.BooleanField(default=True, verbose_name="Ολόημερη")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Ώρα έναρξης"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Ώρα λήξης"),
                ),
                (
                    "worker",
                    models.CharField(
                        blank=True,
                        help_text="Όνομα συνεργάτη ή βοηθητικού",
                        max_length=100,
                        verbose_name="Εργαζόμενος",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=300, verbose_name="Τοποθεσία"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Σημειώσεις")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Προγραμματισμένη"),
                            ("completed", "Ολοκληρωμένη"),
                            ("cancelled", "Ακυρωμένη"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Κατάσταση",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_schedules",
                        to="projects.project",
                        verbose_name="Έργο",
                    ),
                ),
            ],
            options={
                "verbose_name": "Προγραμματισμένη εργασία",
                "verbose_name_plural": "Προγραμματισμένες εργασίες",
                "ordering": ["date", "start_time", "title"],
            },
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("quote_created", "Δημιουργία προσφοράς"),
                    ("quote_updated", "Επεξεργασία προσφοράς"),
                    ("quote_deleted", "Διαγραφή προσφοράς"),
                    ("project_created", "Δημιουργία έργου"),
                    ("project_updated", "Επεξεργασία έργου"),
                    ("project_deleted", "Διαγραφή έργου"),
                    ("income_created", "Καταχώρηση εσόδου"),
                    ("income_updated", "Επεξεργασία εσόδου"),
                    ("income_deleted", "Διαγραφή εσόδου"),
                    ("expense_created", "Καταχώρηση εξόδου έργου"),
                    ("expense_updated", "Επεξεργασία εξόδου έργου"),
                    ("expense_deleted", "Διαγραφή εξόδου έργου"),
                    ("work_hours_created", "Καταχώρηση εργατοωρών"),
                    ("work_schedule_created", "Προγραμματισμός εργασίας"),
                    ("work_schedule_updated", "Επεξεργασία προγραμματισμένης εργασίας"),
                    ("work_schedule_deleted", "Διαγραφή προγραμματισμένης εργασίας"),
                    ("operational_expense_created", "Καταχώρηση λειτουργικού εξόδου"),
                    ("operational_income_created", "Καταχώρηση λειτουργικού εσόδου"),
                    ("customer_created", "Δημιουργία πελάτη"),
                    ("customer_updated", "Επεξεργασία πελάτη"),
                    ("customer_deactivated", "Απενεργοποίηση πελάτη"),
                ],
                max_length=40,
                verbose_name="Ενέργεια",
            ),
        ),
    ]
