# Generated by Django 5.2.14 on 2026-06-19 22:26

import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _slug_username(name: str, used: set[str]) -> str:
    base = re.sub(r"[^a-z0-9]+", "", name.lower()) or "worker"
    username = base
    index = 1
    while username in used:
        username = f"{base}{index}"
        index += 1
    used.add(username)
    return username


def create_profiles_for_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("projects", "UserProfile")

    for user in User.objects.all():
        if user.is_superuser:
            role = "admin"
        elif user.is_staff:
            role = "owner"
        else:
            role = "worker"
        UserProfile.objects.get_or_create(user=user, defaults={"role": role})


def _get_or_create_worker_user(apps, name: str, cache: dict[str, int]):
    name = (name or "").strip()
    if not name:
        return None
    if name in cache:
        return cache[name]

    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("projects", "UserProfile")

    user = User.objects.filter(first_name__iexact=name).first()
    if user is None:
        used = set(User.objects.values_list("username", flat=True))
        username = _slug_username(name, used)
        user = User.objects.create(username=username, first_name=name)
        UserProfile.objects.get_or_create(user=user, defaults={"role": "worker"})
    else:
        UserProfile.objects.get_or_create(user=user, defaults={"role": "worker"})

    cache[name] = user.pk
    return user.pk


def migrate_workhours_workers(apps, schema_editor):
    WorkHours = apps.get_model("projects", "WorkHours")
    cache: dict[str, int] = {}

    for entry in WorkHours.objects.exclude(worker_name=""):
        user_id = _get_or_create_worker_user(apps, entry.worker_name, cache)
        if user_id:
            entry.worker_id = user_id
            entry.save(update_fields=["worker_id"])


def migrate_schedule_workers(apps, schema_editor):
    WorkSchedule = apps.get_model("projects", "WorkSchedule")
    cache: dict[str, int] = {}

    for schedule in WorkSchedule.objects.exclude(worker_name=""):
        user_id = _get_or_create_worker_user(apps, schedule.worker_name, cache)
        if user_id:
            schedule.workers.add(user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_work_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                            ("worker", "Worker"),
                        ],
                        default="worker",
                        max_length=20,
                        verbose_name="Ρόλος",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Χρήστης",
                    ),
                ),
            ],
            options={
                "verbose_name": "Προφίλ χρήστη",
                "verbose_name_plural": "Προφίλ χρηστών",
            },
        ),
        migrations.RunPython(create_profiles_for_users, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="workhours",
            old_name="worker",
            new_name="worker_name",
        ),
        migrations.AddField(
            model_name="workhours",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_hour_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Εργαζόμενος",
            ),
        ),
        migrations.RunPython(migrate_workhours_workers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="workhours",
            name="worker_name",
        ),
        migrations.RenameField(
            model_name="workschedule",
            old_name="worker",
            new_name="worker_name",
        ),
        migrations.AddField(
            model_name="workschedule",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Εργαζόμενοι",
            ),
        ),
        migrations.RunPython(migrate_schedule_workers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="workschedule",
            name="worker_name",
        ),
        migrations.AlterField(
            model_name="quote",
            name="manual_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Σύνολο (χειροκίνητο)",
            ),
        ),
    ]
