# Generated by Django 5.2.14 on 2026-06-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_role_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RolePermission",
        ),
    ]
