# Generated by Django 5.2.14 on 2026-06-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_dynamic_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthRole',
        ),
        migrations.DeleteModel(
            name='AuthRolePermission',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark mode'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('el', 'Ελληνικά'), ('en', 'English')], default='el', max_length=5, verbose_name='Γλώσσα'),
        ),
    ]
