# Generated by Django 5.2.14 on 2026-06-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0016_delete_incomepaymenttypeoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomePaymentTypeOption',
            fields=[
            ],
            options={
                'verbose_name': 'Τύπος πληρωμής',
                'verbose_name_plural': 'Τύποι πληρωμής',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.lookupoption',),
        ),
        migrations.CreateModel(
            name='IncomeTypeOption',
            fields=[
            ],
            options={
                'verbose_name': 'Τύπος εσόδου',
                'verbose_name_plural': 'Τύποι εσόδου',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.lookupoption',),
        ),
        migrations.CreateModel(
            name='OperationalExpenseCategoryOption',
            fields=[
            ],
            options={
                'verbose_name': 'Κατηγορία λειτουργικού εξόδου',
                'verbose_name_plural': 'Κατηγορίες λειτουργικού εξόδου',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.lookupoption',),
        ),
        migrations.CreateModel(
            name='ProjectExpenseCategoryOption',
            fields=[
            ],
            options={
                'verbose_name': 'Κατηγορία εξόδου έργου',
                'verbose_name_plural': 'Κατηγορίες εξόδου έργου',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.lookupoption',),
        ),
        migrations.CreateModel(
            name='QuoteLineCategoryOption',
            fields=[
            ],
            options={
                'verbose_name': 'Κατηγορία γραμμής προσφοράς',
                'verbose_name_plural': 'Κατηγορίες γραμμής προσφοράς',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.lookupoption',),
        ),
        migrations.CreateModel(
            name='QuoteUnitOption',
            fields=[
            ],
            options={
                'verbose_name': 'Μονάδα μέτρησης',
                'verbose_name_plural': 'Μονάδες μέτρησης',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.lookupoption',),
        ),
    ]
