# Generated by Django 5.2.14 on 2026-06-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('projects', '0017_operational_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalIncomeCategoryOption',
            fields=[
            ],
            options={
                'verbose_name': 'Κατηγορία λειτουργικού εσόδου',
                'verbose_name_plural': 'Κατηγορίες λειτουργικού εσόδου',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('projects.lookupoption',),
        ),
    ]
